dist: xenial
language: php
matrix:
  include:
    - php: 7.2
      env: DEPENDENCIES=lowest
    - php: 7.2
      env: DEPENDENCIES=highest
    - php: 7.3
      env: DEPENDENCIES=lowest
    - php: 7.3
      env: DEPENDENCIES=highest
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;
script:
  - bin/phing
after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar && php php-coveralls.phar --verbose --config build/coveralls.yml
notifications:
  email: false
